Repository Hell-Study/Final-Project, pull requests merged in 2023-10, with the labels that each got.

#5 Feat: Binance api 연동 및 환율적용
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/api/binance/fetchExchangeRate.ts
  src/components/Table/Table.styles.ts
  src/components/Table/Table.tsx
  src/components/Table/index.ts
  src/components/Test/index.tsx
  src/hooks/useBinanceTicker.ts
  src/index.tsx
  src/logo.svg
  src/pages/home/Home.page.tsx
  src/pages/home/Home.styles.ts
  src/pages/home/index.ts
  src/recoil/atoms/upbit.ts
  src/recoil/selectors/foo.ts
Labels: enhancement

#14 Feat: 환율 sse api 연동
  .env
  package-lock.json
  package.json
  src/api/binance/fetchExchangeRate.ts
  src/api/bithumb/foo.ts
  src/api/bithumb/getMarketCode.ts
  src/api/upbit/foo.ts
  src/api/upbit/useCreateChart.ts
  src/api/upbit/useFetchMarketCode.ts
  src/api/upbit/useWsTicker.ts
  src/components/ChartLeft/ChartLeft.tsx
  src/components/ChartLeft/index.ts
  src/components/ChartRight/ChartRight.styles.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/ChartRight/index.ts
  src/components/Table/Table.styles.ts
  src/components/Table/Table.tsx
  src/components/Test/index.tsx
  src/components/bithumb/Bithumb.tsx
  src/components/bithumb/Bithumb.type.ts
  src/components/bithumb/BithumbTable.tsx
  src/components/bithumb/index.ts
  src/hooks/binance/useBinanceTicker.ts
  src/hooks/binance/useFetchExchangeRate.ts
  src/hooks/bithumb/useBithumbTicker.ts
  src/hooks/foo.ts
  src/pages/home/Home.page.tsx
  src/pages/home/Home.styles.ts
  src/recoil/atoms/upbit.ts
  src/utils/foo.ts
  src/utils/getTodayDate.ts
Labels: enhancement

#15 Feat: 환율 sse api 연동
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/api/binance/foo.ts
  src/components/Test/index.tsx
  src/hooks/binance/useBinanceTicker.ts
  src/hooks/binance/useFetchExchangeRate.ts
  src/index.tsx
Labels: feat

#20 Feat: 공통 셀렉트 컴포넌트 & 김프 차트 적용
  package-lock.json
  package.json
  src/components/ChartLeft/ChartLeft.constant.ts
  src/components/ChartLeft/ChartLeft.styles.ts
  src/components/ChartLeft/ChartLeft.tsx
  src/components/ChartLeft/TradingViewWidget.tsx
  src/components/ChartLeft/index.ts
  src/components/CustomSelect/CustomSelect.styles.ts
  src/components/CustomSelect/CustomSelect.tsx
  src/components/CustomSelect/index.ts
  src/hooks/useDropdown.ts
  src/recoil/atoms/selectState.ts
Labels: feat

#32 Feat: 다크모드 구현 & 헤더 컴포넌트 스타일링
  package-lock.json
  public/index.html
  src/App.css
  src/App.tsx
  src/assets/images/Logo-Dark.svg
  src/assets/images/Logo-Light.svg
  src/assets/images/foo
  src/assets/style/GlobalStyle.ts
  src/assets/style/theme.ts
  src/components/common/Header/Header.styles.ts
  src/components/common/Header/Header.tsx
  src/hooks/binance/useFetchExchangeRate.ts
  src/hooks/useTheme.ts
  src/recoil/atoms/theme.ts
Labels: feat, Design

#52 Feat: 위젯 + 차트 구현
  package.json
  src/api/getChartWidgetData.ts
  src/api/getTickerWidgetData.ts
  src/assets/style/theme.ts
  src/components/Table/Table.styles.ts
  src/components/Widget/Carousel.tsx
  src/components/Widget/ChartWidget.tsx
  src/components/Widget/TickerWidget.tsx
  src/components/Widget/Widget.constants.ts
  src/components/Widget/Widget.styles.ts
  src/components/Widget/Widget.tsx
  src/components/Widget/Widget.types.ts
  src/components/Widget/index.ts
  src/components/common/Header/Header.styles.ts
  src/hooks/useChartTickers.ts
  src/hooks/useWidgetTickers.ts
  src/pages/home/Home.page.tsx
  src/pages/home/Home.styles.ts
  src/recoil/atoms/prevPriceData.ts
  src/utils/convertTimestamp.ts
  src/utils/formatNumber.ts
  src/utils/getFormattedValues.ts
Labels: feat

#55 Coin 39 feature/table
  src/components/Table/Bithumb.tsx
  src/components/Table/BithumbTable.tsx
  src/components/Table/Table.tsx
  src/components/Table/UpbitTable.tsx
  src/recoil/atoms/common.ts
Labels: feat

#64 Coin 62 feature/optimization
  src/components/ChartLeft/ChartLeft.styles.ts
  src/components/ChartRight/ChartRight.styles.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/Table/Table.styles.ts
  src/components/Widget/Widget.styles.ts
  src/pages/home/Home.styles.ts
Labels: Design

#61 Design: 채팅 스타일링
  src/assets/images/Chat-Btn.svg
  src/assets/images/Chat.svg
  src/assets/style/theme.ts
  src/components/ChatBox/ChatBox.styles.ts
  src/components/ChatBox/ChatBox.tsx
  src/components/Message/Message.styles.ts
  src/components/Message/Message.tsx
  src/components/SendMessage/SendMessage.styles.ts
  src/components/SendMessage/SendMessage.tsx
  src/pages/home/Home.page.tsx
  src/pages/home/Home.styles.ts
Labels: Design

#67 Coin 62 feature/optimization
  package-lock.json
  package.json
  src/App.tsx
  src/api/getGlobalCoinData.ts
  src/api/upbit/useCreateChart.ts
  src/api/upbit/useFetchUpbitMarketCode.ts
  src/components/ChartLeft/ChartLeft.types.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/ChartRight/ChartRight.types.ts
  src/components/ChatBox/ChatBox.tsx
  src/components/ChatBox/ChatBox.types.ts
  src/components/CustomSelect/CustomSelect.tsx
  src/components/Message/Message.tsx
  src/components/Message/Message.types.ts
  src/components/SendMessage/SendMessage.types.ts
  src/components/Table/BithumbTable.tsx
  src/components/Table/Table.types.ts
  src/components/Table/UpbitTable.tsx
  src/components/common/Footer/Footer.types.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/Header.types.ts
  src/firebase/fetchMessages.ts
  src/firebase/messageQuery.ts
  src/firebase/orderSnapshotMessages.ts
  src/hooks/binance/updateUpbitListWithBinance.ts
  src/hooks/upbit/useUpbitTicker.ts
  src/pages/home/Home.types.ts
  src/pages/home/index.ts
Labels: refactor
