Repository Hell-Study/Final-Project, pull requests merged in 2023-11, with the labels that each got.

#69 Design: 김프 차트 스타일링
  src/assets/style/theme.ts
  src/components/ChartLeft/ChartInfo.tsx
  src/components/ChartLeft/ChartLeft.constant.ts
  src/components/ChartLeft/ChartLeft.styles.ts
  src/components/ChartLeft/ChartLeft.tsx
  src/components/ChartLeft/TradingViewWidget.tsx
  src/components/ChartRight/ChartRight.styles.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/CustomSelect/CustomSelect.styles.ts
  src/components/CustomSelect/CustomSelect.tsx
  src/components/CustomSelect/CustomSelect.types.ts
  src/components/Table/Table.constant.ts
  src/components/Table/Table.styles.ts
  src/components/Table/Table.tsx
  src/components/Widget/Widget.styles.ts
  src/pages/home/Home.styles.ts
Labels: Design

#72 Feat: 빗썸 차트 구현
  src/api/bithumb/fetchBithumbCandlestick.ts
  src/components/Table/Bithumb.tsx
  src/components/Table/BithumbTable.tsx
  src/components/bithumb/Bithumb.type.ts
  src/components/bithumb/ChartComponent.tsx
  src/components/bithumb/RealTimeChart.tsx
  src/hooks/binance/updateBithumbSocketDataWithBinance.ts
  src/hooks/bithumb/useBithumbWsTicker.ts
  src/hooks/bithumb/useFetchBithumbticker.ts
  src/hooks/bithumb/useMatchCoingecko.ts
  src/pages/home/Home.page.tsx
  src/recoil/atoms/bithumb.ts
  src/recoil/atoms/common.ts
  src/utils/convertTimestamp.ts
  src/utils/priceCalc.ts
Labels: feat

#74 Feat: 김프 정렬 기능 구현
  src/components/Table/Bithumb.tsx
  src/components/Table/BithumbTable.tsx
  src/components/Table/UpbitTable.tsx
  src/utils/priceCalc.ts
Labels: feat

#77 Design: 테이블 디자인 반영
  src/components/Table/Bithumb.tsx
  src/components/Table/BithumbTable.tsx
  src/components/Table/Table.styles.ts
  src/components/Table/Table.tsx
  src/components/Table/TableHeader/TableHeader.styles.ts
  src/components/Table/TableHeader/TableHeader.tsx
  src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.styles.ts
  src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.tsx
  src/components/Table/TableHeader/TableHeaderItem/index.ts
  src/components/Table/UpbitTable.tsx
Labels: Design

#80 Coin 72 feature/others
  .gitignore
  README.md
  image.png
  package-lock.json
  package.json
  public/index.html
  src/api/getNickname.ts
  src/api/upbit/useCreateChart.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/ChatBox/ChatBox.tsx
  src/components/SendMessage/SendMessage.tsx
  src/components/Table/Table.tsx
  src/firebase/createMessages.ts
  src/firebase/orderSnapshotMessages.ts
  src/hooks/upbit/useUpbitTicker.ts
  src/hooks/useChatboxHelper.ts
Labels: documentation, refactor

#87 Refactor: 정렬 기능 커스텀훅으로 분리
  src/components/Table/TableBox/TableBox.tsx
  src/hooks/index.ts
  src/hooks/useTableSort.ts
Labels: refactor

#86 Feat: 타이틀 김프, 시세 표시 기능 구현
  public/index.html
  public/manifest.json
  src/hooks/useTitle.ts
  src/pages/home/Home.page.tsx
Labels: feat

#94 Refactor: 아이콘 정적 이미지로 변경, 불필요한 리렌더링 개선, windowing 적용 후 성능 개선
  package-lock.json
  package.json
  src/assets/fonts/foo
  src/assets/images/arrow-left-right.svg
  src/assets/images/search.svg
  src/assets/images/sort-down.svg
  src/assets/images/sort-up.svg
  src/components/Table/TableBox/CoinList/CoinChange/CoinChange.tsx
  src/components/Table/TableBox/CoinList/CoinChange/index.ts
  src/components/Table/TableBox/CoinList/CoinHighest/CoinHighest.tsx
  src/components/Table/TableBox/CoinList/CoinHighest/index.ts
  src/components/Table/TableBox/CoinList/CoinInfo/CoinInfo.tsx
  src/components/Table/TableBox/CoinList/CoinInfo/index.ts
  src/components/Table/TableBox/CoinList/CoinKimp/CoinKimp.tsx
  src/components/Table/TableBox/CoinList/CoinKimp/index.ts
  src/components/Table/TableBox/CoinList/CoinList.styles.ts
  src/components/Table/TableBox/CoinList/CoinList.tsx
  src/components/Table/TableBox/CoinList/CoinLowest/CoinLowest.tsx
  src/components/Table/TableBox/CoinList/CoinLowest/index.ts
  src/components/Table/TableBox/CoinList/CoinPrice/CoinPrice.tsx
  src/components/Table/TableBox/CoinList/CoinPrice/index.ts
  src/components/Table/TableBox/CoinList/TradeValue/TradeValue.tsx
  src/components/Table/TableBox/CoinList/TradeValue/index.ts
  src/components/Table/TableBox/CoinList/index.ts
  src/components/Table/TableBox/TableBox.styles.ts
  src/components/Table/TableBox/TableBox.tsx
  src/components/Table/TableHeader/TableHeader.tsx
  src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.styles.ts
  src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.tsx
  src/components/Table/TableNav/TableNav.styles.ts
  src/components/Table/TableNav/TableNav.tsx
  src/components/common/Header/Header.styles.ts
  src/components/common/Header/Header.tsx
Labels: refactor

#96 Refactor: 웹팩 최적화 설정, 리렌더 최소화, 메모제이션 적용
  .gitignore
  config-overrides.js
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  src/App.tsx
  src/assets/images/Chat.svg
  src/assets/images/Logo-Dark.svg
  src/assets/images/Logo-Light.svg
  src/assets/images/binance.svg
  src/assets/images/bithumb.svg
  src/assets/images/btc.svg
  src/assets/images/upbit.svg
  src/assets/images/usdt.svg
  src/components/ChartLeft/ChartLeft.constant.ts
  src/components/ChatBox/ChatBox.styles.ts
  src/components/ChatBtn/ChatBtn.styles.ts
  src/components/ChatBtn/ChatBtn.tsx
  src/components/ChatBtn/index.ts
  src/components/Table/Table.constant.ts
  src/components/Widget/Card.tsx
  src/components/Widget/ChartWidget/ChartWidget.tsx
  src/components/Widget/TickerWidget/TickerWidget.tsx
  src/components/Widget/Widget.styles.ts
  src/components/Widget/Widget.tsx
  src/components/Widget/Widget.types.ts
  src/components/common/Header/ExchangeRateDisplay/ExchangeRateDisplay.styles.ts
  src/components/common/Header/ExchangeRateDisplay/ExchangeRateDisplay.tsx
  src/components/common/Header/ExchangeRateDisplay/index.ts
  src/components/common/Header/GlobalCoinLabel/GlobalCoinLabel.styles.ts
  src/components/common/Header/GlobalCoinLabel/GlobalCoinLabel.tsx
  src/components/common/Header/GlobalCoinLabel/index.ts
  src/components/common/Header/Header.styles.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/Header.types.ts
  src/hooks/binance/useBinanceTicker.ts
  src/pages/home/Home.page.tsx
  src/pages/home/Home.styles.ts
Labels: refactor

#91 Coin 82 feature/others
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/Caret-Down.svg
  src/assets/images/Caret-Up.svg
  src/assets/images/Check.svg
  src/assets/images/Chevron-Down.svg
  src/assets/images/Chevron-Left.svg
  src/assets/images/Chevron-Right.svg
  src/assets/images/Github.svg
  src/assets/images/Loading.json
  src/assets/images/MessageDots.svg
  src/assets/images/Moon.svg
  src/assets/images/Paper-Plane.svg
  src/assets/images/Sun.svg
  src/components/ChartRight/ChartRight.styles.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/ChatBox/ChatBox.styles.ts
  src/components/ChatBox/ChatBox.tsx
  src/components/CustomSelect/CustomSelect.styles.ts
  src/components/CustomSelect/CustomSelect.tsx
  src/components/LoadingAnimation/LoadingAnimation.styles.ts
  src/components/LoadingAnimation/LoadingAnimation.tsx
  src/components/LoadingAnimation/index.ts
  src/components/SendMessage/SendMessage.styles.ts
  src/components/SendMessage/SendMessage.tsx
  src/components/Table/TableNav/TableNav.styles.ts
  src/components/Widget/Carousel/Carousel.tsx
  src/components/Widget/TickerWidget/TickerWidget.tsx
  src/components/Widget/Widget.styles.ts
  src/components/common/Footer/Footer.styles.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/index.ts
  src/components/common/Header/Header.styles.ts
  src/components/common/Header/Header.tsx
  src/hooks/useChatboxHelper.ts
  src/pages/home/Home.page.tsx
Labels: refactor

#98 Refactor: 차트 컴포넌트화
  package-lock.json
  package.json
  public/apple-touch-icon.png
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/robots.txt
  src/components/ChartRight/ChartCoinInfo/ChartCoinInfo.styles.ts
  src/components/ChartRight/ChartCoinInfo/ChartCoinInfo.tsx
  src/components/ChartRight/ChartCoinInfo/index.ts
  src/components/ChartRight/ChartContent/ChartContent.styles.ts
  src/components/ChartRight/ChartContent/ChartContent.tsx
  src/components/ChartRight/ChartContent/index.ts
  src/components/ChartRight/ChartRight.styles.ts
  src/components/ChartRight/ChartRight.tsx
  src/components/Table/Table.styles.ts
  src/components/Table/TableBox/TableBox.tsx
  src/components/Table/TableBox/index.ts
  src/components/Table/TableNav/TableNav.styles.ts
  src/components/Widget/TickerWidget/TickerWidget.tsx
Labels: refactor

#102 Coin 72 feature/others
  README.md
Labels: documentation

#106 Docs: 서지수 역할 수정
  README.md
Labels: documentation

#104 Refactor: 코인 차트 memo를 이용한 리렌더링 방지
  src/components/ChatBox/ChatBox.tsx
  src/components/CustomSelect/CustomSelect.tsx
  src/components/Table/TableHeader/TableHeader.tsx
  src/components/Table/TableHeader/index.ts
  src/components/Table/TableNav/TableNav.styles.ts
  src/components/Table/TableNav/TableNav.tsx
  src/components/Table/TableNav/TableNavSelect/TableNavSelect.constant.ts
  src/components/Table/TableNav/TableNavSelect/TableNavSelect.styles.ts
  src/components/Table/TableNav/TableNavSelect/TableNavSelect.tsx
  src/components/Table/TableNav/TableNavSelect/index.ts
  src/components/Table/TableNav/index.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/ExchangeRateDisplay/ExchangeRateDisplay.styles.ts
  src/components/common/Header/GlobalCoinLabel/GlobalCoinLabel.tsx
  src/components/common/Header/Header.tsx
  src/firebase/messageQuery.ts
Labels: refactor

#105 Design: 코인 차트 다크모드 적용
  src/components/ChartRight/ChartContent/ChartContent.tsx
  src/recoil/atoms/commonAtoms.ts
Labels: Design
